### ISSUE TITLE
add support for "key is missing", for example by "!key" or "key not present"

### ISSUE THREAD

**Issue by matkoniecz** [tyrasd/overpass-wizard#5]
At least for me searching for cases where some key or keys are nor present is a typical task. Currently it is impossible to generate such queries with wizard and in addition syntax for achieving that is quite cumbersome.

----

https://github.com/westnordost/StreetComplete is supporting first version in its internal equivalent of overpass-wizard

see for example https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/recycling/AddRecyclingType.java#L21

where query is

> nodes, ways, relations with amenity = recycling and !recycling_type"

!recycling type should be translated to

> "recycling_type"!~".*"

**Comment by tyrasd** [comment]
isn't `recycling_type != *` ([*Matches objects that do not have a tag with the key.*](https://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard#Tag_Searches)) what you're looking for? Example: http://overpass-turbo.eu/s/sar

**Comment by matkoniecz** [comment]
Yes, thanks and sorry for noise
